#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  CREATE EXTENSION IF NOT EXISTS "pgcrypto";
  CREATE DATABASE keycloak;
  CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';
  GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
EOSQL
