logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.pintailconsultingllc.auth: ERROR

spring:
  application:
    name: "Authentication and authorization microservice"
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    enabled: false
    changeLog: classpath:db/db.changelog-master.yaml
  security:
    user:
      name: auth-user
      password: Yh5bnd8%7gHHtrs

springdoc:
  swagger-ui:
    operationsSorter: method
    filter: true
    deep-linking: true

---

spring:
  profile: local
  liquibase:
    enabled: true


logging:
  level:
    .: INFO
    org.springframework: INFO
    com.pintailconsultingllc.auth: DEBUG
