#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  CREATE EXTENSION IF NOT EXISTS "pgcrypto";
  CREATE DATABASE product;
  CREATE USER product WITH ENCRYPTED PASSWORD 'product';
  GRANT ALL PRIVILEGES ON DATABASE product TO product;
EOSQL
