version: '3.7'

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: ${POSTGRES_REPOSITORY}:13-alpine
    container_name: saga-pattern-postgres
    restart: always
    volumes:
      - ./keycloak/postgresql/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - ./product/postgresql/init.sh:/docker-entrypoint-initdb.d/0002-initialization.sh
      - ./inventory/postgresql/init.sh:/docker-entrypoint-initdb.d/0003-initialization.sh
      - ./ecommerce/postgresql/init.sh:/docker-entrypoint-initdb.d/0004-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: ${REDIS_REPOSITORY}:alpine
    ports:
      - 16379:6379
#    volumes:
#      - ./redis-data:/var/lib/redis
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: saga-pattern-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 18080:8080
      - 18443:8443
    depends_on:
      - postgres

