version: '3.7'
services:
  product-db:
    image: ${POSTGRES_REPOSITORY}:13-alpine
    hostname: saga-example-db
    container_name: saga-example-db
    restart: always
    volumes:
      - ./product/postgresql/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: saga-example
      POSTGRES_PASSWORD: saga-example

volumes:
  db-data:
    driver: local
