version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "p4$$w0rD"

volumes:
  db_data: