version: '3.7'

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: ${POSTGRES_REPOSITORY}:13-alpine
    container_name: saga-pattern-postgres
    restart: always
    volumes:
      - ./auth/postgresql/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - ./product/postgresql/init.sh:/docker-entrypoint-initdb.d/0002-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: ${REDIS_REPOSITORY}:alpine
    ports:
      - 16379:6379
#    volumes:
#      - ./redis-data:/var/lib/redis
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

