version: '3.7'
services:
  product-db:
    image: postgres:13-alpine
    hostname: product-db
    container_name: product-db
    # command: postgres -c 'encrypt.key=dfd76a78d6fasdf68df'
    restart: always
    volumes:
      - ./product/postgresql/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      # Persist the data between container invocations
      - db-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      ANON: web_anon
      AUTHENTICATOR: authenticator

volumes:
  db-data:
    driver: local
