logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.pintailconsultingllc.product: ERROR

spring:
  application:
    name: "Product microservice"
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    enabled: false
    changeLog: classpath:db/db.changelog-master.yaml
  security:
    user:
      name: product-user
      password: Yh5bnd8%7gHHtrs

---

spring:
  profile: local
  liquibase:
    enabled: true


logging:
  level:
    .: INFO
    org.springframework: INFO
    com.pintailconsultingllc.product: DEBUG